<!-- EXPORT: TITULO -->
<div style="
background:#ffffff;
padding:35px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">

<h1 style="
font-size:55px;
color:#ef4444;
text-align:center;
margin-top:0;
margin-bottom:10px;
">
Caso de Negocio 3
</h1>

<h2 style="
font-size:35px;
color:#1f2937;
text-align:center;
font-weight:normal;
margin-top:0;
margin-bottom:25px;
">
Análisis de la Evolución de los Indicadores Monetarios y Financieros de Guatemala (2015–2025)
</h2>

<hr style="border:5px solid #cbd5e1; margin-bottom:30px;">
<hr style="border:3px solid #cbd5e1; margin-bottom:30px;">
<hr style="border:1px solid #cbd5e1; margin-bottom:30px;">

</div>

<div style="
background:#ffffff;
padding:35px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">


<h3 style="
font-size:35px;
color:#ef4444;
margin-bottom:10px;
">
Contexto del negocio
</h3>

<!-- EXPORT: CONTEXTO -->
<div style="
background:#ffffff;
padding:35px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">

<p style="
font-size:17px;
color:#374151;
line-height:1.8;
text-align:justify;
">
El Banco Central de Guatemala requiere monitorear la evolución de los principales indicadores monetarios y financieros para comprender el comportamiento de la liquidez, el crédito al sector privado, las remesas familiares y la actividad económica del país. El objetivo es generar información que apoye la toma de decisiones relacionadas con la estabilidad financiera y el seguimiento del crecimiento económico.
</p>



</div>

<div style="
background:#ffffff;
padding:35px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">


<h3 style="
font-size:35px;
color:#ef4444;
margin-bottom:10px;
">
Objetivo general
</h3>

<!-- EXPORT: OBJETIVO -->
<div style="
background:#ffffff;
padding:35px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">


<p style="
font-size:17px;
color:#374151;
line-height:1.8;
text-align:justify;
">
Analizar la evolución de los principales indicadores monetarios de Guatemala durante el período 2015–2025 para identificar tendencias, relaciones entre variables y posibles factores asociados al crecimiento económico y la liquidez del sistema financiero.
</p>

</div>

<div style="
background:#ffffff;
padding:30px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">

<h2 style="
font-size:35px;
color:#ef4444;
text-align:center;
margin-top:0;
margin-bottom:30px;
">
Preguntas de negocio
</h2>

<ol style="
font-size:17px;
color:#374151;
line-height:2;
padding-left:25px;
">

<li><b>¿Cómo evolucionaron los principales agregados monetarios durante el período?</b></li>

<li><b>¿Existe relación entre el crecimiento del PIB y el crédito bancario al sector privado?</b></li>

<li><b>¿Las remesas familiares presentan relación con el crecimiento de los medios de pago (M2)?</b></li>

<li><b>¿Cómo evolucionó el spread bancario en moneda nacional y moneda extranjera?</b></li>

<li><b>¿Qué indicador presentó el mayor crecimiento durante el período?</b></li>

<li><b>¿Cuál ha sido la variación trimestral del PIB?</b></li>

<li><b>¿Existe una relación entre el crecimiento de las remesas y el PIB?</b></li>

</ol>

</div>

In [2]:
# Librerias
import sys
sys.path.append("..")

import numpy as np
import pandas as pd

from math import pi
from bokeh.layouts import column
from bokeh.models import (
    ColumnDataSource,
    CustomJS,
    DatetimeTickFormatter,
    GlobalInlineStyleSheet,
    HoverTool,
    Label,
    Legend,
    LegendItem,
    NumeralTickFormatter,
    RangeTool,
    TapTool,
    LabelSet, 
    Span
)
from bokeh.plotting import figure, show, output_notebook
from bokeh.transform import dodge, factor_cmap

from utils import export_tables
from utils import export_charts
from utils import export_text

In [3]:
#Tema
output_notebook()

THEMES = {
    "economic_modern": {
        "BACKGROUND": "#faf7f5",
        "PANEL": "#ffffff",
        "GRID": "#d6d3d1",
        "GRID_ALPHA": 0.45,
        "BORDER": "#cbd5e1",
        "TEXT": "#1f2937",
        "TEXT_SOFT": "#64748b",
        "TEXT_SIZE": "10pt",
        "ACCENT": "#ef4444",
        "POSITIVE": "#22c55e",
        "NEGATIVE": "#dc2626",
        "WARNING": "#f59e0b",
        "COLORS": {
            "PIB": "#2563eb",         
            "NUMERARIO": "#f97316",   
            "CREDITO": "#16a34a",     
            "M2": "#9333ea",           
            "REMESAS": "#eab308",      
            "SPREAD_MN": "#dc2626",    
            "SPREAD_ME": "#06b6d4"     
        }
    }
}

theme = THEMES["economic_modern"]
colors = theme["COLORS"]

Loading BokehJS ...

In [4]:
# Tables and Charts

TABLES = {}
CHARTS = {}

In [5]:
#Base de datos
df = pd.read_csv("../data/caso_3_lim.csv")
df.columns.name = None
TABLES["table"] = df
df

,Trimestre,Año,numerario en circulacion,credito bancario total al sector privado,medios de pagos totales,spread bancario en mn,spread bancario en me,remesas familiares,PIB Trimestral
0,1,2015,70278.3,465675.2,558854.6,8.03%,3.03%,10677.93,"117,897.3"
1,2,2015,71145.8,470759.0,564714.4,7.94%,3.02%,11991.96,"116,183.4"
2,3,2015,73002.3,475810.1,571462.5,7.83%,2.98%,12584.58,"118,716.5"
3,4,2015,73663.8,480657.7,574962.5,7.75%,2.95%,12949.65,"123,225.6"
4,1,2016,77432.8,518424.9,604368.3,7.59%,3.01%,12796.27,"123,838.5"
5,2,2016,77830.9,520442.7,611167.3,7.61%,3.03%,14215.73,"122,799.4"
6,3,2016,79324.2,523964.6,614850.4,7.65%,3.06%,13336.83,"124,518.0"
7,4,2016,83048.9,536542.8,628914.3,7.67%,3.10%,14168.37,"130,845.7"
8,1,2017,89216.9,544840.4,641288.3,7.61%,3.04%,14434.38,"131,682.7"
9,2,2017,90815.3,549986.5,656254.7,7.63%,3.02%,15522.05,"127,650.4"


<!-- EXPORT: PREGUNTA_1 -->
<div style="
background:#ffffff;
padding:30px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">

<ol style="
font-size:25px;
color:#374151;
line-height:1.5;
padding-left:25px;
">
    
<b>¿Cómo evolucionaron los principales agregados monetarios durante el período?</b>
</ol>

</div>

In [6]:
# Data Question 1

variable_ques1 = ["numerario en circulacion", "credito bancario total al sector privado", 
                  "medios de pagos totales", "remesas familiares", "PIB Trimestral"]
df_ques1 = df[["Año", "Trimestre"] + variable_ques1]
df_ques1["Periodo"] = (df_ques1["Año"].astype(str) + "-T"+ df_ques1["Trimestre"].astype(str))
df_ques1["Fecha"] = pd.to_datetime(df_ques1["Año"].astype(str) + "-" + ((df_ques1["Trimestre"] - 1) * 3 + 1).astype(str) + "-01")

for col in variable_ques1: 
    df[col] = (df[col].astype(str).str.replace(",", "", regex=False).astype(float))

for var in variable_ques1: 
    df_ques1[var] = df[var] / df[var].iloc[0] * 100

source = ColumnDataSource(df_ques1)
df_ques1.columns.name = None
TABLES["table_ques1"] = df_ques1
df_ques1

,Año,Trimestre,numerario en circulacion,credito bancario total al sector privado,medios de pagos totales,remesas familiares,PIB Trimestral,Periodo,Fecha
0,2015,1,100.000000,100.000000,100.000000,100.000000,100.000000,2015-T1,2015-01-01
1,2015,2,101.234378,101.091705,101.048537,112.306037,98.546277,2015-T2,2015-04-01
2,2015,3,103.876019,102.176388,102.256025,117.855989,100.694842,2015-T3,2015-07-01
3,2015,4,104.817276,103.217371,102.882306,121.274910,104.519442,2015-T4,2015-10-01
4,2016,1,110.180241,111.327573,108.144104,119.838489,105.039301,2016-T1,2016-01-01
5,2016,2,110.746703,111.760880,109.360700,133.131890,104.157941,2016-T2,2016-04-01
6,2016,3,112.871541,112.517179,110.019744,124.900894,105.615650,2016-T3,2016-07-01
7,2016,4,118.171470,115.218247,112.536302,132.688358,110.982779,2016-T4,2016-10-01
8,2017,1,126.948005,117.000089,114.750474,135.179571,111.692719,2017-T1,2017-01-01
9,2017,2,129.222392,118.105173,117.428523,145.365722,108.272539,2017-T2,2017-04-01


In [7]:
#Chart Question 1
p_ques1 = figure(
    width=950,
    height=450,
    x_axis_type="datetime",
    title="Evolución de los principales agregados monetarios (Base 100)",
    background_fill_color=theme["BACKGROUND"],
    border_fill_color=theme["PANEL"],
    tools="pan,wheel_zoom,box_zoom,reset,save"
)
p_ques1 .line(
    "Fecha",
    "numerario en circulacion",
    source=source,
    color=colors["NUMERARIO"],
    line_width=3,
    legend_label="Numerario"
)

p_ques1 .line(
    "Fecha",
    "credito bancario total al sector privado",
    source=source,
    color=colors["CREDITO"],
    line_width=3,
    legend_label="Crédito"
)

p_ques1 .line(
    "Fecha",
    "medios de pagos totales",
    source=source,
    color=colors["M2"],
    line_width=3,
    legend_label="M2"
)

p_ques1 .line(
    "Fecha",
    "remesas familiares",
    source=source,
    color=colors["REMESAS"],
    line_width=3,
    legend_label="Remesas"
)

p_ques1 .line(
    "Fecha",
    "PIB Trimestral",
    source=source,
    color=colors["PIB"],
    line_width=3,
    legend_label="PIB"
)

hover = HoverTool(
    tooltips="""
    <div style="
        background:#1f1720;
        border:1px solid #ff6b81;
        border-radius:8px;
        padding:8px;
        color:white;
    ">
        <b>Fecha:</b> @Periodo<br>
        <b>Valor:</b> $y{0.0}
    </div>
    """
)

p_ques1 .add_tools(hover)
p_ques1 .stylesheets = [
    GlobalInlineStyleSheet(css="""
    .bk-Tooltip {
        --tooltip-color: transparent !important;
        --tooltip-border: transparent !important;
    }
    .bk-tooltip-content {
        background: transparent !important;
        border: none !important;
        box-shadow: none !important;
        padding: 0 !important;
    }
    """)
]
p_ques1.legend.location = "top_left"
p_ques1.legend.orientation = "vertical"
p_ques1.legend.background_fill_color = theme["PANEL"]
p_ques1.legend.background_fill_alpha = 0.9
p_ques1.legend.border_line_color = theme["BORDER"]
p_ques1.legend.label_text_color = theme["TEXT"]
p_ques1.legend.label_text_font_size = "10pt"
p_ques1.legend.padding = 8
p_ques1.legend.spacing = 6
p_ques1.legend.margin = 5
p_ques1.legend.click_policy = "hide"
p_ques1.yaxis.formatter = NumeralTickFormatter(format="0.00a")
p_ques1.toolbar.logo = None
p_ques1.toolbar.autohide = True
p_ques1.title.text_color = theme["ACCENT"] 
p_ques1.title.text_font_size = "20pt"        
p_ques1.title.align = "center"  
p_ques1.yaxis.axis_label = 'Saldos'
p_ques1.yaxis.axis_label_text_color = theme["TEXT"]
p_ques1.xaxis.major_label_text_color = theme["TEXT_SOFT"]
p_ques1.yaxis.major_label_text_color = theme["TEXT_SOFT"]
p_ques1.outline_line_color = theme["BORDER"]
p_ques1.xgrid.grid_line_color = theme["GRID"]
p_ques1.ygrid.grid_line_color = theme["GRID"]
p_ques1.xgrid.grid_line_alpha = theme["GRID_ALPHA"]
p_ques1.ygrid.grid_line_alpha = theme["GRID_ALPHA"]

select = figure(
    title="Seleccionar período",
    height=120,
    width=950,
    x_axis_type="datetime",
    y_axis_type=None,
    tools="",
    toolbar_location=None,
    background_fill_color=theme["BACKGROUND"],
    border_fill_color=theme["PANEL"]
)
select.line("Fecha", "medios de pagos totales", source=source, color=colors["M2"])
range_tool = RangeTool(x_range=p_ques1.x_range)
range_tool.overlay.fill_color = theme["ACCENT"]
range_tool.overlay.fill_alpha = 0.25
select.add_tools(range_tool)

CHARTS["chart_ques1"] = column(p_ques1)
show(column(p_ques1, select))

<!-- EXPORT: ANALISIS_1 -->
<div style="
background:#ffffff;
padding:25px;
border-left:6px solid #cbd5e1;
border-radius:10px;
margin:20px 0;
color:#e0e0e0;        
">

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
Durante el período comprendido entre 2015 y 2025, los principales agregados monetarios de Guatemala muestran una tendencia general de crecimiento sostenido. El Producto Interno Bruto (PIB) presenta la evolución más estable y moderada, reflejando un crecimiento económico constante a lo largo del período. Por su parte, los medios de pago (M2) y el crédito bancario al sector privado registran un crecimiento superior al del PIB, manteniendo igualmente una trayectoria estable y con baja volatilidad. Finalmente, el numerario en circulación y las remesas familiares son las variables que experimentan el mayor crecimiento relativo, aunque las remesas destacan por presentar fluctuaciones más pronunciadas durante algunos trimestres.
</p>

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
Las diferencias en el comportamiento de estas variables pueden asociarse a su naturaleza económica. Mientras que el PIB, el crédito bancario, los medios de pago y el numerario en circulación responden principalmente a las condiciones macroeconómicas internas y a la política monetaria implementada por el Banco de Guatemala, las remesas familiares dependen en mayor medida de factores externos, como la situación económica de los países de origen de los migrantes, las condiciones del mercado laboral internacional y los cambios en las políticas migratorias. Esta dependencia explica la mayor volatilidad observada en dicha variable.
</p>

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
Desde una perspectiva de política económica, los resultados evidencian que el seguimiento de las remesas familiares y del numerario en circulación resulta especialmente relevante debido a la magnitud de su crecimiento y a la influencia que ejercen sobre la liquidez de la economía. No obstante, el análisis de estos indicadores debe complementarse con variables como el crédito bancario, los medios de pago y el PIB, ya que en conjunto proporcionan una visión más completa de la evolución del sistema monetario y financiero del país y permiten fundamentar de mejor manera la toma de decisiones.
</p>


</div>

<!-- EXPORT: PREGUNTA_2 -->
<div style="
background:#ffffff;
padding:30px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">

<ol style="
font-size:25px;
color:#374151;
line-height:1.5;
padding-left:25px;
">
    
<b>¿Existe relación entre el crecimiento del PIB y el crédito bancario al sector privado?</b></ol>

</div>

In [8]:
# Data Question 2
df_ques2 = df[["Trimestre","Año","credito bancario total al sector privado", "PIB Trimestral"]]
df_ques2["Año"] = df_ques2["Año"].astype(str)
source = ColumnDataSource(df_ques2)
df_ques2.columns.name = None
TABLES["table_ques2"] = df_ques2
df_ques2

,Trimestre,Año,credito bancario total al sector privado,PIB Trimestral
0,1,2015,465675.2,117897.3
1,2,2015,470759.0,116183.4
2,3,2015,475810.1,118716.5
3,4,2015,480657.7,123225.6
4,1,2016,518424.9,123838.5
5,2,2016,520442.7,122799.4
6,3,2016,523964.6,124518.0
7,4,2016,536542.8,130845.7
8,1,2017,544840.4,131682.7
9,2,2017,549986.5,127650.4


In [9]:
# Chart Question 2

p_ques2 = figure(
    height=400, width=800,
    tools="pan,wheel_zoom,reset,save,tap",
    x_axis_label="Crédito Bancario",
    y_axis_label="PIB",
    background_fill_color=theme["BACKGROUND"],
    border_fill_color=theme["PANEL"],
    title="Relación Crédito Bancario - PIB"
)

renderer = p_ques2.scatter(
    x="credito bancario total al sector privado",
    y="PIB Trimestral",
    source=source,
    size=9,
    color=colors["CREDITO"],  
    alpha=0.8
)

hover = HoverTool(
    tooltips="""
    <div style="
        background:#0b0b0b;
        border:1px solid #d4af37;
        border-radius:6px;
        padding:8px;
        color:#fff;
    ">
        <div><b>Año:</b> @Año</div>
        <div><b>Trimestre:</b> @Trimestre</div>
        <div><b>Crédito Bancario:</b> @{credito bancario total al sector privado}{0,0.00}</div>
        <div><b>PIB:</b> @{PIB Trimestral}{0,0.00}</div>
    </div>
    """,
    renderers=[renderer]
)

p_ques2.add_tools(hover)
taptool = p_ques2.select(type=TapTool)
p_ques2.yaxis.formatter = NumeralTickFormatter(format="0.00a")
p_ques2.xaxis.formatter = NumeralTickFormatter(format="0.00a")
p_ques2.title.text_color = theme["ACCENT"] 
p_ques2.title.text_font_size = "20pt"        
p_ques2.title.align = "center"  
p_ques2.xaxis.axis_label_text_color = theme["TEXT"]
p_ques2.yaxis.axis_label_text_color = theme["TEXT"]
p_ques2.xaxis.major_label_text_color = theme["TEXT_SOFT"]
p_ques2.yaxis.major_label_text_color = theme["TEXT_SOFT"]
p_ques2.outline_line_color = theme["BORDER"]
p_ques2.xgrid.grid_line_color = theme["GRID"]
p_ques2.ygrid.grid_line_color = theme["GRID"]
p_ques2.xgrid.grid_line_alpha = theme["GRID_ALPHA"]
p_ques2.ygrid.grid_line_alpha = theme["GRID_ALPHA"]
p_ques2.toolbar.logo = None
p_ques2.toolbar.autohide = True

CHARTS["chart_ques2"] = p_ques2
show(p_ques2)

<!-- EXPORT: ANALISIS_2 -->
<div style="
background:#ffffff;
padding:25px;
border-left:6px solid #cbd5e1;
border-radius:10px;
margin:20px 0;
color:#e0e0e0;        
">

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
El crédito bancario total al sector privado presenta una relación lineal positiva con el Producto Interno Bruto (PIB), evidenciando que conforme la economía ha crecido durante el período analizado, también lo ha hecho el financiamiento otorgado al sector privado. Este comportamiento refleja la estrecha relación existente entre la actividad económica y la expansión del crédito, ya que ambos indicadores tienden a evolucionar de manera conjunta en escenarios de crecimiento económico.
</p>

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
No obstante, se observa un punto atípico correspondiente al segundo trimestre de 2020, período en el que la pandemia de COVID-19 provocó una fuerte contracción de la actividad económica. Las restricciones sanitarias, la disminución de la producción y los cambios en las políticas empresariales y financieras alteraron temporalmente la relación histórica entre ambas variables, generando una desviación respecto de la tendencia observada en el resto de la serie.
</p>

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
En términos generales, la relación observada sugiere que el crecimiento del crédito y el desempeño del PIB se encuentran estrechamente vinculados. Por ello, las decisiones de política monetaria y financiera deben considerar el comportamiento conjunto de ambos indicadores, ya que cambios significativos en uno de ellos pueden influir en la dinámica del otro y, en consecuencia, en el desempeño de la economía nacional.
</p>
</div>

<!-- EXPORT: PREGUNTA_3 -->
<div style="
background:#ffffff;
padding:30px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">

<ol style="
font-size:25px;
color:#374151;
line-height:1.5;
padding-left:25px;
">
    
<b>¿Las remesas familiares presentan relación con el crecimiento de los medios de pago (M2)?</b>
</ol>

</div>


In [10]:
# Data Question 3
df_ques3 = df[["Trimestre","Año","medios de pagos totales", "remesas familiares"]]
df_ques3["Año"] = df_ques3["Año"].astype(str)
source = ColumnDataSource(df_ques3)
df_ques3.columns.name = None
TABLES["table_ques3"] = df_ques3
df_ques3

,Trimestre,Año,medios de pagos totales,remesas familiares
0,1,2015,558854.6,10677.93
1,2,2015,564714.4,11991.96
2,3,2015,571462.5,12584.58
3,4,2015,574962.5,12949.65
4,1,2016,604368.3,12796.27
5,2,2016,611167.3,14215.73
6,3,2016,614850.4,13336.83
7,4,2016,628914.3,14168.37
8,1,2017,641288.3,14434.38
9,2,2017,656254.7,15522.05


In [11]:
#Chart Question 3

p_ques3 = figure(
    height=550, 
    width=950,
    tools="pan,wheel_zoom,reset,save,tap",
    x_axis_label="remesas familiares",
    y_axis_label="M2",
    background_fill_color=theme["BACKGROUND"],
    border_fill_color=theme["PANEL"],
    title="Relación Remesas Familiares - Medios de Pago (M2)"
)

renderer = p_ques3.scatter(
    x="remesas familiares",
    y="medios de pagos totales",
    source=source,
    size=9,
    color=colors["M2"],
    alpha=0.8
)

hover = HoverTool(
    tooltips="""
    <div style="
        background:#0b0b0b;
        border:1px solid #d4af37;
        border-radius:6px;
        padding:8px;
        color:#fff;
    ">
        <div><b>Año:</b> @Año</div>
        <div><b>Trimestre:</b> @Trimestre</div>
        <div><b>M2:</b> @{medios de pagos totales}{0,0.00}</div>
        <div><b>Remesas:</b> @{remesas familiares}{0,0.00}</div>
    </div>
    """,
    renderers=[renderer]
)

p_ques3.add_tools(hover)

taptool = p_ques3.select(type=TapTool)
p_ques3.yaxis.formatter = NumeralTickFormatter(format="0.00a")
p_ques3.xaxis.formatter = NumeralTickFormatter(format="0.00a")
p_ques3.title.text_color = theme["ACCENT"] 
p_ques3.title.text_font_size = "20pt"        
p_ques3.title.align = "center"  
p_ques3.xaxis.axis_label_text_color = theme["TEXT"]
p_ques3.yaxis.axis_label_text_color = theme["TEXT"]
p_ques3.xaxis.major_label_text_color = theme["TEXT_SOFT"]
p_ques3.yaxis.major_label_text_color = theme["TEXT_SOFT"]
p_ques3.outline_line_color = theme["BORDER"]
p_ques3.xgrid.grid_line_color = theme["GRID"]
p_ques3.ygrid.grid_line_color = theme["GRID"]
p_ques3.xgrid.grid_line_alpha = theme["GRID_ALPHA"]
p_ques3.ygrid.grid_line_alpha = theme["GRID_ALPHA"]
p_ques3.toolbar.logo = None
p_ques3.toolbar.autohide = True

CHARTS["chart_ques3"] = p_ques3
show(p_ques3)

<!-- EXPORT: ANALISIS_3 -->
<div style="
background:#ffffff;
padding:25px;
border-left:6px solid #cbd5e1;
border-radius:10px;
margin:20px 0;
color:#e0e0e0;        
">

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
Las remesas familiares y los medios de pago (M2) presentan una relación lineal positiva durante el período 2015–2025. A medida que el flujo de remesas aumenta, también se observa un crecimiento sostenido de los medios de pago, evidenciando una asociación entre ambas variables. Este comportamiento es consistente con el papel que desempeñan las remesas dentro de la economía guatemalteca, ya que una parte importante de estos recursos ingresa al sistema financiero y contribuye al incremento de la liquidez.
</p>

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
A partir de 2019 se aprecia una ligera dispersión en la nube de puntos, generando un patrón tipo abanico. Este comportamiento coincide con el período en el que las remesas familiares mostraron una mayor volatilidad, principalmente durante los años de la pandemia y la posterior recuperación económica. No obstante, la tendencia general continúa siendo creciente, por lo que la asociación positiva entre ambas variables se mantiene.
</p>

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
En términos de política económica, la relación observada sugiere que el seguimiento de las remesas familiares resulta relevante para evaluar la evolución de la liquidez del sistema financiero. Debido a que las remesas están expuestas a factores externos, como el desempeño económico de los países de origen de los migrantes y cambios en el contexto internacional, es recomendable que las autoridades monetarias y las instituciones financieras monitoreen su comportamiento como un indicador complementario para la toma de decisiones.
</p>
</div>

<!-- EXPORT: PREGUNTA_4 -->
<div style="
background:#ffffff;
padding:30px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">

<ol style="
font-size:25px;
color:#374151;
line-height:1.5;
padding-left:25px;
">
<b>¿Cómo evolucionó el spread bancario en moneda nacional y moneda extranjera?</b>
</ol>

</div>


In [12]:
# Data Qyestion 4

variable_ques4 = ["spread bancario en mn ", "spread bancario en me"]
df_ques4 = df[["Año", "Trimestre"] + variable_ques4]
df_ques4["Periodo"] = (df_ques4["Año"].astype(str) + "-T"+ df_ques4["Trimestre"].astype(str))
df_ques4["Fecha"] = pd.to_datetime(df_ques4["Año"].astype(str) + "-" + ((df_ques4["Trimestre"] - 1) * 3 + 1).astype(str) + "-01")

for col in variable_ques4:
    df[col] = (df[col].astype(str).str.replace("%", "", regex=False).astype(float)/ 100)
    
for col in variable_ques4: 
    df[col] = (df[col].astype(str).str.replace(",", "", regex=False).astype(float))

for var in variable_ques4: 
    df_ques4[var] = df[var] / df[var].iloc[0] * 100

source = ColumnDataSource(df_ques4)
df_ques4.columns.name = None
TABLES["table_ques4"] = df_ques4
df_ques4

,Año,Trimestre,spread bancario en mn,spread bancario en me,Periodo,Fecha
0,2015,1,100.000000,100.000000,2015-T1,2015-01-01
1,2015,2,98.879203,99.669967,2015-T2,2015-04-01
2,2015,3,97.509340,98.349835,2015-T3,2015-07-01
3,2015,4,96.513076,97.359736,2015-T4,2015-10-01
4,2016,1,94.520548,99.339934,2016-T1,2016-01-01
5,2016,2,94.769614,100.000000,2016-T2,2016-04-01
6,2016,3,95.267746,100.990099,2016-T3,2016-07-01
7,2016,4,95.516812,102.310231,2016-T4,2016-10-01
8,2017,1,94.769614,100.330033,2017-T1,2017-01-01
9,2017,2,95.018680,99.669967,2017-T2,2017-04-01


In [13]:
# Chart Question 4

p_ques4 = figure(
    width=950,
    height=450,
    x_axis_type="datetime",
    title="Evolución del spread bancario en MN y ME (Base 100)",
    background_fill_color=theme["BACKGROUND"],
    border_fill_color=theme["PANEL"],
    tools="pan,wheel_zoom,box_zoom,reset,save"
)
p_ques4.line(
    "Fecha",
    "spread bancario en mn ",
    source=source,
    color=colors["SPREAD_MN"],
    line_width=3,
    legend_label="Spread MN"
)

p_ques4.line(
    "Fecha",
    "spread bancario en me",
    source=source,
    color=colors["SPREAD_ME"],
    line_width=3,
    legend_label="Spread ME"
)


hover = HoverTool(
    tooltips="""
    <div style="
        background:#1f1720;
        border:1px solid #ff6b81;
        border-radius:8px;
        padding:8px;
        color:white;
    ">
        <b>Fecha:</b> @Periodo<br>
        <b>Valor:</b> $y{0.0}
    </div>
    """
)

p_ques4.add_tools(hover)
p_ques4.legend.location = "top_left"
p_ques4.legend.orientation = "vertical"
p_ques4.legend.background_fill_color = theme["PANEL"]
p_ques4.legend.background_fill_alpha = 0.9
p_ques4.legend.border_line_color = theme["BORDER"]
p_ques4.legend.label_text_color = theme["TEXT"]
p_ques4.legend.label_text_font_size = "10pt"
p_ques4.legend.padding = 8
p_ques4.legend.spacing = 6
p_ques4.legend.margin = 5
p_ques4.legend.click_policy = "hide"
p_ques4.yaxis.formatter = NumeralTickFormatter(format="0.00a")
p_ques4.toolbar.logo = None
p_ques4.toolbar.autohide = True
p_ques4.title.text_color = theme["ACCENT"] 
p_ques4.title.text_font_size = "20pt"        
p_ques4.title.align = "center"  
p_ques4.yaxis.axis_label = 'Saldos'
p_ques4.yaxis.axis_label_text_color = theme["TEXT"]
p_ques4.xaxis.major_label_text_color = theme["TEXT_SOFT"]
p_ques4.yaxis.major_label_text_color = theme["TEXT_SOFT"]
p_ques4.outline_line_color = theme["BORDER"]
p_ques4.xgrid.grid_line_color = theme["GRID"]
p_ques4.ygrid.grid_line_color = theme["GRID"]
p_ques4.xgrid.grid_line_alpha = theme["GRID_ALPHA"]
p_ques4.ygrid.grid_line_alpha = theme["GRID_ALPHA"]

select = figure(
    title="Seleccionar período",
    height=120,
    width=950,
    x_axis_type="datetime",
    y_axis_type=None,
    tools="",
    toolbar_location=None,
    background_fill_color=theme["BACKGROUND"],
    border_fill_color=theme["PANEL"]
)

select.line(
    "Fecha",
    "spread bancario en mn ",
    source=source,
    color=colors["SPREAD_MN"]
)
range_tool = RangeTool(x_range=p_ques4.x_range)
range_tool.overlay.fill_color = theme["ACCENT"]
range_tool.overlay.fill_alpha = 0.25
select.add_tools(range_tool)

CHARTS["chart_ques4"] = column(p_ques4)
show(column(p_ques4, select))

<!-- EXPORT: ANALISIS_4 -->
<div style="
background:#ffffff;
padding:25px;
border-left:6px solid #cbd5e1;
border-radius:10px;
margin:20px 0;
color:#e0e0e0;        
">

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
La evolución del spread bancario en moneda nacional (MN) y moneda extranjera (ME) presenta diferencias importantes durante el período analizado. Tomando como referencia el primer trimestre de 2015 (índice base 100), el spread bancario en moneda nacional muestra una tendencia descendente y relativamente estable, con una variación aproximada entre 100.5 y 92.3. Por su parte, el spread bancario en moneda extranjera evidencia una mayor amplitud en sus fluctuaciones, alcanzando valores entre 113.9 y 97.4, lo que refleja una mayor variabilidad respecto a su período base.
</p>

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
A partir de 2019 el spread bancario en moneda extranjera incrementa su volatilidad, comportamiento que comienza a moderarse hacia 2023. En contraste, el spread en moneda nacional mantiene un comportamiento más estable, aunque desde finales de 2021 inicia una reducción gradual que lo lleva a registrar su nivel mínimo durante el último trimestre de 2024. Estas variaciones coinciden temporalmente con un período de elevada incertidumbre económica internacional, caracterizado por los efectos de la pandemia de COVID-19 y posteriormente por el conflicto entre Rusia y Ucrania, eventos que influyeron sobre las condiciones financieras y los mercados internacionales.
</p>

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
En conjunto, los resultados sugieren que el spread bancario en moneda nacional ha mantenido un comportamiento relativamente más estable que el observado en moneda extranjera. Esta diferencia puede interpretarse como un reflejo de la mayor sensibilidad de las operaciones denominadas en moneda extranjera frente a factores externos, mientras que el mercado en moneda nacional tiende a responder principalmente a las condiciones monetarias y financieras internas. Por ello, el seguimiento conjunto de ambos indicadores constituye una herramienta relevante para evaluar la estabilidad del sistema financiero y la evolución de las condiciones de financiamiento en el país.
</p>
</div>

<!-- EXPORT: PREGUMTA_5 -->
<div style="
background:#ffffff;
padding:30px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">

<ol style="
font-size:25px;
color:#374151;
line-height:1.5;
padding-left:25px;
">

<b>¿Qué indicador presentó el mayor crecimiento acumulado entre 2015 y 2025?</b>
</ol>

</div>

In [14]:
# Data Question 5

variables_ques5 = ["numerario en circulacion", "credito bancario total al sector privado", 
                   "medios de pagos totales", "remesas familiares", "PIB Trimestral"]
nombres = ["Numerario", "Crédito", "M2", "Remesas", "PIB"]
crecimiento = []

for var, nombre in zip(variables_ques5, nombres):
    porcentaje = ((df[var].iloc[-1] / df[var].iloc[0]) - 1) * 100
    crecimiento.append({"Indicador": nombre, "Crecimiento": porcentaje})

df_ques5 = (pd.DataFrame(crecimiento).sort_values("Crecimiento", ascending=False).reset_index(drop=True))
df_ques5["Crecimiento_txt"] = df_ques5["Crecimiento"].round(1).astype(str) + "%"
source = ColumnDataSource(df_ques5)
df_ques5.columns.name = None
TABLES["table_ques5"] = df_ques5
df_ques5

,Indicador,Crecimiento,Crecimiento_txt
0,Remesas,371.689644,371.7%
1,Numerario,313.697400,313.7%
2,M2,181.483610,181.5%
3,Crédito,162.701621,162.7%
4,PIB,111.092196,111.1%


In [15]:
# Chart Question 5

p_ques5 = figure(
    y_range=list(df_ques5["Indicador"])[::-1],
    x_range=(0, 450), 
    height=400,
    width=800,
    title="Crecimiento acumulado de los indicadores (2015-2025)",
    background_fill_color=theme["BACKGROUND"],
    border_fill_color=theme["PANEL"],
    tools="pan,wheel_zoom,reset,save"
)

renderer = p_ques5.hbar(
    y="Indicador",
    right="Crecimiento",
    height=0.75,
    source=source,
    color=theme["ACCENT"]
)

labels = LabelSet(
    x="Crecimiento",       
    y="Indicador",         
    text="Crecimiento_txt", 
    level="glyph",
    x_offset=10,           
    y_offset=0,             
    source=source,
    text_font_size="10pt",
    text_color=theme["TEXT"]
)

hover = HoverTool(
    tooltips="""
    <div style="
        background:#ffffff;
        border:1px solid #ff6b81;
        border-radius:8px;
        padding:8px;
        color:#374151;
    ">
        <div><b>Indicador:</b> @Indicador</div>
        <div><b>Crecimiento:</b> @Crecimiento{0.0}%</div>
    </div>
    """,
    renderers=[renderer]
)

p_ques5.add_layout(labels)
p_ques5.add_tools(hover)
p_ques5.xaxis.major_label_orientation = 1.0  
p_ques5.title.text_color = theme["ACCENT"] 
p_ques5.title.text_font_size = "20pt"        
p_ques5.title.align = "center"  
p_ques5.xaxis.axis_label_text_color = theme["TEXT"]
p_ques5.yaxis.axis_label_text_color = theme["TEXT"]
p_ques5.xaxis.major_label_text_color = theme["TEXT_SOFT"]
p_ques5.yaxis.major_label_text_color = theme["TEXT_SOFT"]
p_ques5.outline_line_color = theme["BORDER"]
p_ques5.xgrid.grid_line_color = theme["GRID"]
p_ques5.ygrid.grid_line_color = theme["GRID"]
p_ques5.xgrid.grid_line_alpha = theme["GRID_ALPHA"]
p_ques5.ygrid.grid_line_alpha = theme["GRID_ALPHA"]
p_ques5.toolbar.logo = None
p_ques5.toolbar.autohide = True

CHARTS["chart_ques5"] = p_ques5
show(p_ques5)

<!-- EXPORT: ANALISIS_5 -->
<div style="
background:#ffffff;
padding:25px;
border-left:6px solid #cbd5e1;
border-radius:10px;
margin:20px 0;
color:#e0e0e0;        
">

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
El crecimiento acumulado de los principales indicadores monetarios y financieros durante el período 2015–2025 evidencia que las remesas familiares fueron la variable con mayor expansión, registrando un incremento aproximado del <b>371.7%</b> respecto al período base. En segundo lugar se ubicó el numerario en circulación con un crecimiento cercano al <b>313.7%</b>, mientras que los medios de pago (M2), el crédito bancario al sector privado y el Producto Interno Bruto (PIB) mostraron incrementos más moderados, comprendidos entre el <b>111.1%</b> y el <b>181.5%</b>.
</p>

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
Estos resultados reflejan que, durante la última década, las remesas familiares se consolidaron como uno de los principales motores del crecimiento económico y de la expansión de la liquidez en Guatemala. Asimismo, el importante aumento del numerario en circulación sugiere que el efectivo continúa desempeñando un papel predominante dentro de las transacciones económicas del país, situación que puede estar asociada con una elevada utilización del dinero en efectivo y con los desafíos que aún existen en materia de inclusión financiera.
</p>

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
En conjunto, el comportamiento de estos indicadores muestra que el crecimiento del sistema monetario no ha sido homogéneo entre todas las variables. Mientras el PIB y el crédito bancario mantuvieron una evolución más estable y consistente con el crecimiento económico de largo plazo, las remesas familiares y el numerario fueron los componentes que registraron la mayor dinámica de expansión, resaltando su importancia dentro de la economía guatemalteca y su potencial influencia sobre la liquidez y el consumo interno.
</p>

</div>

<!-- EXPORT: PREGUMTA_6 -->
<div style="
background:#ffffff;
padding:30px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">

<ol style="
font-size:25px;
color:#374151;
line-height:1.5;
padding-left:25px;
">
    
<b>¿Cuál ha sido la variación trimestral del PIB?</b>
</ol>

</div>

In [16]:
# Data Question 6

df_ques6 = df[["Año", "Trimestre", "PIB Trimestral"]].copy()
df_ques6["Fecha"] = pd.to_datetime(df_ques6["Año"].astype(str) + "-" + ((df_ques6["Trimestre"] - 1) * 3 + 1).astype(str) + "-01")
df_ques6["Variación %"] = (df_ques6["PIB Trimestral"].pct_change() * 100)
df_ques6["Color"] = np.where(df_ques6["Variación %"] >= 0, theme["POSITIVE"], theme["NEGATIVE"])
df_ques6 = df_ques6.dropna().reset_index(drop=True)
source = ColumnDataSource(df_ques6)
df_ques6.columns.name = None
TABLES["table_ques6"] = df_ques6
df_ques6

,Año,Trimestre,PIB Trimestral,Fecha,Variación %,Color
0,2015,2,116183.4,2015-04-01,-1.453723,#dc2626
1,2015,3,118716.5,2015-07-01,2.180260,#22c55e
2,2015,4,123225.6,2015-10-01,3.798208,#22c55e
3,2016,1,123838.5,2016-01-01,0.497380,#22c55e
4,2016,2,122799.4,2016-04-01,-0.839077,#dc2626
5,2016,3,124518.0,2016-07-01,1.399518,#22c55e
6,2016,4,130845.7,2016-10-01,5.081755,#22c55e
7,2017,1,131682.7,2017-01-01,0.639685,#22c55e
8,2017,2,127650.4,2017-04-01,-3.062133,#dc2626
9,2017,3,130291.7,2017-07-01,2.069167,#22c55e


In [17]:
# Chart Question 6

p_ques6 = figure(
    width=900,
    height=420,
    x_axis_type="datetime",
    title="Variación trimestral del PIB",
    tools="pan,wheel_zoom,box_zoom,reset,save",
    background_fill_color=theme["BACKGROUND"],
    border_fill_color=theme["PANEL"]
)

renderer = p_ques6.vbar(
    x="Fecha",
    top="Variación %",
    width=70*24*60*60*1000,     
    source=source,
    fill_color="Color",
    line_color="Color"
)

# Línea en cero
p_ques6.add_layout(
    Span(
        location=0,
        dimension="width",
        line_color=theme["TEXT_SOFT"],
        line_dash="dashed",
        line_width=2
    )
)

hover = HoverTool(
    renderers=[renderer],
    tooltips="""
    <div style="
        background:#1f1720;
        border:1px solid #ff6b81;
        border-radius:8px;
        padding:8px;
        color:white;
    ">
        <b>Año:</b> @Año<br>
        <b>Trimestre:</b> @Trimestre<br>
        <b>Variación:</b> @{Variación %}{0.00}%<br>
        <b>PIB:</b> @{PIB Trimestral}{0,0.00}
    </div>
    """
)
p_ques6.yaxis.axis_label = "Variación (%)"
p_ques6.yaxis.formatter = NumeralTickFormatter(format="0.0")
p_ques6.yaxis.major_label_overrides = {}
p_ques6.add_layout(labels)
p_ques6.add_tools(hover)
p_ques6.xaxis.major_label_orientation = 1.0  
p_ques6.title.text_color = theme["ACCENT"] 
p_ques6.title.text_font_size = "20pt"        
p_ques6.title.align = "center"  
p_ques6.xaxis.axis_label_text_color = theme["TEXT"]
p_ques6.yaxis.axis_label_text_color = theme["TEXT"]
p_ques6.xaxis.major_label_text_color = theme["TEXT_SOFT"]
p_ques6.yaxis.major_label_text_color = theme["TEXT_SOFT"]
p_ques6.outline_line_color = theme["BORDER"]
p_ques6.xgrid.grid_line_color = theme["GRID"]
p_ques6.ygrid.grid_line_color = theme["GRID"]
p_ques6.xgrid.grid_line_alpha = theme["GRID_ALPHA"]
p_ques6.ygrid.grid_line_alpha = theme["GRID_ALPHA"]
p_ques6.toolbar.logo = None
p_ques6.toolbar.autohide = True

CHARTS["chart_ques6"] = p_ques6
show(p_ques6)

<!-- EXPORT: ANALISIS_6 -->
<div style="
background:#ffffff;
padding:25px;
border-left:6px solid #cbd5e1;
border-radius:10px;
margin:20px 0;
color:#e0e0e0;        
">

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
La variación trimestral del Producto Interno Bruto (PIB) muestra un comportamiento claramente diferenciado antes y después del año 2020. Durante el período comprendido entre 2015 y 2019 se observa un patrón estacional relativamente estable, caracterizado por un crecimiento importante en el cuarto trimestre de cada año y una desaceleración o variación negativa en el segundo trimestre en la mayoría de los períodos analizados. Este comportamiento refleja la existencia de ciclos económicos recurrentes asociados a la dinámica productiva nacional.
</p>

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
El año 2020 representa un punto de quiebre en la serie histórica debido a la crisis provocada por la pandemia de COVID-19. Como consecuencia de las restricciones sanitarias y la paralización parcial de las actividades económicas, el PIB registró una contracción significativa durante los dos primeros trimestres, alcanzando una variación mínima cercana al -9.73%. Posteriormente, la reapertura gradual de la economía permitió una rápida recuperación de la actividad productiva, reflejada en una variación positiva cercana al 9.98% durante el tercer trimestre, constituyendo el mayor crecimiento observado en todo el período de estudio.
</p>

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
A partir de 2022 la economía guatemalteca retomó un comportamiento más estable, registrando tasas de crecimiento moderadas y sin variaciones trimestrales negativas significativas. Asimismo, vuelve a apreciarse el patrón estacional observado antes de la pandemia, lo que sugiere un proceso de normalización de la actividad económica tras el choque extraordinario experimentado en 2020. En conjunto, estos resultados evidencian la resiliencia de la economía guatemalteca y su capacidad para recuperar la senda de crecimiento una vez superado el período de mayor incertidumbre.
</p>

</div>

<div style="
background:#ffffff;
padding:30px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">

<ol style="
font-size:25px;
color:#374151;
line-height:1.5;
padding-left:25px;
">
<!-- EXPORT: PREGUMTA_7 -->
    
<b>¿Existe una relación entre el crecimiento de las remesas y el PIB?</b>
</ol>

</div>

In [18]:
# Data Question 7

df_ques7 = df[["Trimestre", "Año", "remesas familiares", "PIB Trimestral"]]
df_ques7["Año"] = df_ques7["Año"].astype(str)
source = ColumnDataSource(df_ques7)
df_ques7.columns.name = None
TABLES["table_ques7"] = df_ques7
df_ques7

,Trimestre,Año,remesas familiares,PIB Trimestral
0,1,2015,10677.93,117897.3
1,2,2015,11991.96,116183.4
2,3,2015,12584.58,118716.5
3,4,2015,12949.65,123225.6
4,1,2016,12796.27,123838.5
5,2,2016,14215.73,122799.4
6,3,2016,13336.83,124518.0
7,4,2016,14168.37,130845.7
8,1,2017,14434.38,131682.7
9,2,2017,15522.05,127650.4


In [19]:
# Chart Question 7

p_ques7 = figure(
    height=550, 
    width=950,
    tools="pan,wheel_zoom,reset,save,tap",
    x_axis_label="Remesas familiares",
    y_axis_label="PIB",
    background_fill_color=theme["BACKGROUND"],
    border_fill_color=theme["PANEL"],
    title="Relación Remesas familiares - PIB"
)

renderer = p_ques7.scatter(
    x="remesas familiares",
    y="PIB Trimestral",
    source=source,
    size=9,
    color=colors["REMESAS"],  
    alpha=0.8
)

hover = HoverTool(
    tooltips="""
    <div style="
        background:#0b0b0b;
        border:1px solid #d4af37;
        border-radius:6px;
        padding:8px;
        color:#fff;
    ">
        <div><b>Año:</b> @Año</div>
        <div><b>Trimestre:</b> @Trimestre</div>
        <div><b>Remesas familiares:</b> @{remesas familiares}{0,0.00}</div>
        <div><b>PIB:</b> @{PIB Trimestral}{0,0.00}</div>
    </div>
    """,
    renderers=[renderer]
)

p_ques7.add_tools(hover)


taptool = p_ques7.select(type=TapTool)

p_ques7.yaxis.formatter = NumeralTickFormatter(format="0.00a")
p_ques7.xaxis.formatter = NumeralTickFormatter(format="0.00a")
p_ques7.title.text_color = theme["ACCENT"] 
p_ques7.title.text_font_size = "20pt"        
p_ques7.title.align = "center"  
p_ques7.xaxis.axis_label_text_color = theme["TEXT"]
p_ques7.yaxis.axis_label_text_color = theme["TEXT"]
p_ques7.xaxis.major_label_text_color = theme["TEXT_SOFT"]
p_ques7.yaxis.major_label_text_color = theme["TEXT_SOFT"]
p_ques7.outline_line_color = theme["BORDER"]
p_ques7.xgrid.grid_line_color = theme["GRID"]
p_ques7.ygrid.grid_line_color = theme["GRID"]
p_ques7.xgrid.grid_line_alpha = theme["GRID_ALPHA"]
p_ques7.ygrid.grid_line_alpha = theme["GRID_ALPHA"]
p_ques7.toolbar.logo = None
p_ques7.toolbar.autohide = True

CHARTS["chart_ques7"] = p_ques7
show(p_ques7)

<!-- EXPORT: ANALISIS_7 -->
<div style="
background:#ffffff;
padding:25px;
border-left:6px solid #cbd5e1;
border-radius:10px;
margin:20px 0;
color:#e0e0e0;        
">

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
El comportamiento observado evidencia que el crecimiento de las remesas familiares ha estado acompañado por una expansión del Producto Interno Bruto (PIB) durante el período 2015–2025. A medida que aumenta el ingreso de divisas provenientes del exterior, también se incrementa la capacidad de consumo e inversión de los hogares receptores, lo que contribuye al dinamismo de distintos sectores de la economía y favorece el crecimiento de la producción nacional.
</p>

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
Aunque a partir de 2019 la dispersión de los datos es ligeramente mayor, principalmente por los efectos económicos derivados de la pandemia de COVID-19, la trayectoria general continúa mostrando un comportamiento creciente. Esto indica que, aun bajo escenarios de incertidumbre, las remesas mantuvieron un papel importante como fuente de ingresos para los hogares guatemaltecos y como mecanismo de apoyo para la recuperación de la actividad económica.</p>

<p style="
font-size:15px;
color:#374151;
line-height:1.5;
text-align:justify;
">
Desde una perspectiva macroeconómica, estos resultados resaltan la relevancia de las remesas dentro del modelo económico guatemalteco. Sin embargo, también evidencian una dependencia significativa de recursos provenientes del exterior, los cuales pueden verse afectados por cambios en las condiciones económicas internacionales, el mercado laboral de los países donde residen los migrantes o modificaciones en las políticas migratorias. Por ello, resulta conveniente que las autoridades económicas complementen este flujo de ingresos con políticas orientadas a fortalecer la inversión, la productividad y la generación de empleo interno, reduciendo gradualmente la dependencia de factores externos como fuente de crecimiento económico.
</p>
</div>

<div style="
background:#ffffff;
padding:35px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">

<h1 style="
font-size:35px;
color:#ef4444;
text-align:center;
margin-top:0;
margin-bottom:10px;
">
Conclusiones y Recomendaciones
</h1>

<hr style="border:5px solid #cbd5e1; margin-bottom:30px;">

</div>


<div style="
background:#ffffff;
padding:35px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">

<h3 style="
font-size:35px;
color:#ef4444;
margin-bottom:10px;
">
Conclusiones
</h3>

<!-- EXPORT: CONCLUSIONES -->
<div style="
background:#ffffff;
padding:35px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">

<ul style="
font-size:17px;
color:#374151;
line-height:1.8;
text-align:justify;
">

<li>Durante el período 2015–2025, la economía guatemalteca mostró una tendencia de crecimiento sostenido en la mayoría de los indicadores monetarios y financieros analizados, siendo las remesas familiares y el numerario en circulación las variables que registraron el mayor crecimiento acumulado.</li>

<li>Los análisis realizados evidencian una asociación positiva entre el Producto Interno Bruto (PIB) y variables como el crédito bancario, los medios de pago (M2) y las remesas familiares, lo que refleja la estrecha relación existente entre la actividad económica, la liquidez y el financiamiento del sector privado.</li>

<li>El spread bancario en moneda nacional presentó un comportamiento más estable que el spread en moneda extranjera, lo cual sugiere que el mercado financiero interno ofrece menores fluctuaciones frente a los cambios originados por factores externos.</li>

<li>Las remesas familiares constituyen uno de los principales motores de la liquidez y del crecimiento económico del país. Sin embargo, su elevada participación también evidencia una importante dependencia de ingresos provenientes del exterior, situación que representa un riesgo ante posibles cambios en el entorno económico internacional.</li>

<li>La evolución del PIB permitió identificar un patrón estacional relativamente estable que únicamente fue interrumpido durante la pandemia de COVID-19, período en el que la economía experimentó una fuerte contracción seguida por un proceso gradual de recuperación y normalización.</li>

</ul>

</div>


<div style="
background:#ffffff;
padding:35px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">

<h3 style="
font-size:35px;
color:#ef4444;
margin-top:35px;
margin-bottom:10px;
">
Recomendaciones
</h3>

<!-- EXPORT: RECOMEMDACIONES -->
<div style="
background:#ffffff;
padding:35px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">

<ul style="
font-size:17px;
color:#374151;
line-height:1.8;
text-align:justify;
">

<li>Las instituciones financieras y los organismos encargados de la política económica deberían mantener un monitoreo permanente de indicadores como las remesas familiares, el numerario en circulación y los medios de pago, debido a su estrecha relación con la evolución de la actividad económica nacional.</li>

<li>Para estudios orientados a la formulación de políticas públicas o decisiones estratégicas, se recomienda complementar este análisis descriptivo con modelos econométricos que permitan cuantificar el impacto y la causalidad entre las variables analizadas.</li>

<li>Es recomendable utilizar información estadística actualizada y revisar periódicamente las series publicadas por el Banco de Guatemala, ya que las cifras más recientes pueden ser objeto de revisiones o ajustes metodológicos.</li>

<li>Finalmente, resulta conveniente impulsar políticas que fortalezcan la inclusión financiera y promuevan una mayor bancarización, con el propósito de reducir la dependencia del efectivo y canalizar una mayor proporción de los recursos provenientes de remesas hacia el sistema financiero formal.</li>

</ul>

</div>


<div style="
background:#ffffff;
padding:35px;
border:3px solid #cbd5e1;
border-radius:15px;
margin:20px 0;
">

<h1 style="
font-size:55px;
color:#ef4444;
text-align:center;
margin-top:0;
margin-bottom:10px;
">
Exportar Proyecto
</h1>

<hr style="border:5px solid #ef4444; margin-bottom:30px;">

</div>



In [20]:
#Export Tables

export_tables.exportar_tablas(TABLES)

-> Tabla 'table.tex' exportada con éxito en la carpeta '../tables/'.
-> Tabla 'table_ques1.tex' exportada con éxito en la carpeta '../tables/'.
-> Tabla 'table_ques2.tex' exportada con éxito en la carpeta '../tables/'.
-> Tabla 'table_ques3.tex' exportada con éxito en la carpeta '../tables/'.
-> Tabla 'table_ques4.tex' exportada con éxito en la carpeta '../tables/'.
-> Tabla 'table_ques5.tex' exportada con éxito en la carpeta '../tables/'.
-> Tabla 'table_ques6.tex' exportada con éxito en la carpeta '../tables/'.
-> Tabla 'table_ques7.tex' exportada con éxito en la carpeta '../tables/'.
Todas las tablas fueron exportadas correctamente.


In [21]:
#Export Charts

export_charts.exportar_graficas(CHARTS)

-> chart_ques1.png exportada


-> chart_ques2.png exportada


-> chart_ques3.png exportada


-> chart_ques4.png exportada


-> chart_ques5.png exportada


-> chart_ques6.png exportada


-> chart_ques7.png exportada


Todas las gráficas fueron exportadas correctamente.


In [22]:
#Export Text

export_text.exportar_reporte_textos("caso 3.ipynb")

-> 'titulo.tex' guardado en '../text/'
-> 'contexto.tex' guardado en '../text/'
-> 'objetivo.tex' guardado en '../text/'
-> 'pregunta_1.tex' guardado en '../text/'


-> 'analisis_1.tex' guardado en '../text/'
-> 'pregunta_2.tex' guardado en '../text/'
-> 'analisis_2.tex' guardado en '../text/'
-> 'pregunta_3.tex' guardado en '../text/'
-> 'analisis_3.tex' guardado en '../text/'
-> 'pregunta_4.tex' guardado en '../text/'
-> 'analisis_4.tex' guardado en '../text/'
-> 'pregumta_5.tex' guardado en '../text/'
-> 'analisis_5.tex' guardado en '../text/'
-> 'pregumta_6.tex' guardado en '../text/'
-> 'analisis_6.tex' guardado en '../text/'
-> 'pregumta_7.tex' guardado en '../text/'
-> 'analisis_7.tex' guardado en '../text/'
-> 'conclusiones.tex' guardado en '../text/'
-> 'recomemdaciones.tex' guardado en '../text/'
Textos exportados correctamente.
